// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzokleaDsoo0vK-2eoRP_L5I61Nd6M2L4',
    appId: '1:701494836215:web:1f20a46217dde83d7c4cf2',
    messagingSenderId: '701494836215',
    projectId: 'hongsi-347511',
    authDomain: 'hongsi-347511.firebaseapp.com',
    databaseURL: 'https://hongsi-347511-default-rtdb.firebaseio.com',
    storageBucket: 'hongsi-347511.appspot.com',
    measurementId: 'G-XTBEMTHB6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jr5UWkGxIxnAXPOEHp65XSa2GL389H0',
    appId: '1:701494836215:android:58ac51858f89bf807c4cf2',
    messagingSenderId: '701494836215',
    projectId: 'hongsi-347511',
    databaseURL: 'https://hongsi-347511-default-rtdb.firebaseio.com',
    storageBucket: 'hongsi-347511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Er1KOzT64vSlX6PNSHCDWzNmr58nAgk',
    appId: '1:701494836215:ios:067632004500bbff7c4cf2',
    messagingSenderId: '701494836215',
    projectId: 'hongsi-347511',
    databaseURL: 'https://hongsi-347511-default-rtdb.firebaseio.com',
    storageBucket: 'hongsi-347511.appspot.com',
    androidClientId: '701494836215-i5g1gg1d9r52pu49qr7pfuim44uvn5go.apps.googleusercontent.com',
    iosClientId: '701494836215-nbglumiqqq0e3b93pj49n74vd75cs434.apps.googleusercontent.com',
    iosBundleId: 'com.example.hongsiProject',
  );
}
